### ISSUE TITLE
Selective support pandoc's markdown

### ISSUE THREAD

**Issue by Jocs** [marktext/marktext#1525]
## What's Pandoc?

Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library.

>[Pandoc](https://pandoc.org/MANUAL.html#pandocs-markdown) understands an extended and slightly revised version of John Gruber’s Markdown syntax.

## Planed to support pandoc's markdown syntax

- [ ] Heading identifiers #688 
- [ ] Line blocks
- [ ] Definition list
- [ ] table_captions
- [ ] Superscripts and subscripts #195 
- [x] tex_math_dollars, only support LaTeX now, and  $...$ (for inline math) or $$...$$ (for display math) #1188 #176 
- [ ] Internal links, this will be supported after `heading identifiers`
- [ ] fenced_divs #1516  #1240
- [ ] bracketed_spans, use this syntax we can use it to highlight text.
- [ ] footnotes #193 and inline_notes
- [ ] citations #1316 #1358 

Welcome everyone to add the list above

**Comment by fxha** [comment]
> tex_math_dollars, only support LaTeX now, and $...$ (for inline math) or $$...$$ (for display math) 

@Jocs Regarding the quote above: That's not true because we only support `$$\n<text>\n$$` display math but pandoc allow `$$...$$` (without new line) too.

**Comment by s1291** [comment]
What about cross references for equations?

**Comment by Jocs** [comment]
>What about cross references for equations?

Any documents about `cross references for equations`？

**Comment by s1291** [comment]
Hello,
I am not quite sure, but I think this is not yet implemented in Pandoc:
https://github.com/jgm/pandoc/issues/5581

**Comment by pihentagy** [comment]
Will this be added to Jopline once when ALL of the above will be ready, or is it possible to add those subtasks one-by-one when ready?

**Comment by Jocs** [comment]
Yeh, they will be add one-by-one, not all of them above at same time.
