### ISSUE TITLE
Tracking issue: source code editor

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2188]
This issue tracks the improvements of the source editor. The source editor is an extension to the preview editor and has lower priority because we focus on the stabitlty and improvements on Muya (our core/rich text engine). While the source editor provides basic editing, it's missing some features such as undo and redo.

**TODO's:**

- [ ] Find and replace (#1864)
- [ ] Undo and redo (#781)
- [ ] Auto-bullets (#1140)
- [ ] Paste handler: HTML to markdown conversion (#1329)
- [ ] Menu support (#1431)
- [ ] Enable virtual rendering (there was an issue so we have to disable it)

Please feel free to contribute on these issues. Any development will be tracked here.
