### ISSUE TITLE
Document is modified when opened/Markdown formatting

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2189]
### Overview

The goal of this issue is to clarify automatically markdown formatting and the modification notification without any document interaction and further steps to improve the situation.

### My document is automatically formatted

Some would say this is a great feature and others don't. Mark Text formats all content according CommonMark and GFM (+other extensions if enabled). The reason for this is that we don't store the document as string with spaces etc but as block structure with minimal information. As a side effect, we need to build the text file when saving the document. In some situations, we don't know the formatting of the original document and apply the default style according markdown specification.

### Why is my document modified after opened?

That's an issue with our data structure/flow and cursor positioning but will hopefully fix soon as we (@Jocs) refactor the data structure and get rid of the old data flow. This should also bring better performance and extension support the core of the editor.

### Next steps

It's currently not planned to change the markdown formatting as it's built-in into the editor but as we continuously improve our engine, and we'll keep this issue in mind and try our best to overwrite as little as possible. The removal of empty lines is currently not addressed as it would require a significant work to our markdown parser and data structure.

**TODO's:**

This is a non-exclusive list for improvements that require changes to the markdown parser, data structure and other parts of the core engine:

- [ ] List formatting (keep original list style)
- [ ] Keep old ordered lists numbering; that's against markdown specification -> settinngs options (?)
- [ ] SetExt heading count
- [ ] Footnote positioning (see #2036)
- [ ] Don't style table cells

Please feel free to contribute on these issues. Any development will be tracked here.

**Comment by brainchild0** [comment]
Thanks for opening this topic. Since the discussion on this question so far has been, I think, fragmented, taking it into a central issue topic is extremely helpful.

I think the core of the discussion is exactly the following:

> Some would say this is a great feature and others don't.

It is useful to note that the  the application might  include support for rewriting the formatting elements (i.e. markup) of the document without doing so as a side effect of document editing. For example, in principle, a menu command might produce this effect, but only when manually invoked by the user (e.g. "Clean document formatting").


I am glad that it is considered a bug    that  unmodified document buffers are marked as modified. However, whether the unmodified document is marked as modified is simply a special case of whether unmodified parts of an edited document are modified in the raw file.

A very common case for editing Markdown documents is changing part of a document, and desiring a resulting file as close as possible  to the original, in terms of lines, words, and characters, that includes the  modifications. For example, in this use,   inserting a single word, through the editing buffer, in some existing paragraph, would have the sole effect of adding that word to the raw document.  Reasons for this needing this behavior include integration with revision tracking systems and inclusion of non-standard formatting.   I believe that this use, for whatever reasons in each case,  is common enough that supporting it is necessary for an editor to become a popular and reliable application within  the Markdown community.

Clearly, as observed, this functionality depends on a more sophisticated internal representation of the document. I am wondering though whether the functionality  is possible through very minimal enhancements to the document tree. It would  be necessary only  to include with each node the original string representation   (or offset bounds of some static buffer).  Following a  change to some  part of a document in the editing buffer,  the node might be marked dirty, or the string cleared, for a new value to be generated when the document is saved.

**Comment by aisbergde** [comment]
> Mark Text formats all content according CommonMark and GFM (+other extensions if enabled). The reason for this is that we don't store the document as string with spaces etc but as block structure with minimal information.

Thank you very much for the explanation. Now I understand some behaviors much better get a better idea how it works and why. I think this information is very important and should be available on a prominent place in the documentation, may even on the readme file.

Knowing that you can understand marktext as an translator in well formatted markdown and use it this way. Don't knowing this you could be disappointed about marktext destroying content.

**Comment by aisbergde** [comment]
> It would seem necessary only to include with each node the original string representation (or offset bounds of some static buffer).

this would also allow to make changes to the raw text visible, which is normally not possible in "normal" editors, but can be done in Word. For example when I get the message that the file has changed it would be possible to compare changes.

**Comment by amartin3225** [comment]
I would also find it very helpful to keep ordered lists as a series of "1." rather than renumbering when opened in Mark Text

**Comment by axelsimon** [comment]
Not sure if this is where to add this, but rather than open a new issue i'll comment here first:
MarkText adds a lot of extraneous line breaks when formatting in Markdown. For instance, a bullet list i'd expect to be structured like this:
```Markdown
this is a list:
- item 1
- item 2
- item 3
```

but the actual text file looks more like this:
```Markdown
this is a list:

- item 1

- item 2

- item 3
```

**Comment by brainchild0** [comment]
(@axelsimon: Please see #2310.)

**Comment by laurent-simon** [comment]
Automatic formatting can be a great feature, but only if it is done on demand. Currently, has it is, it is more a problem than a feature for my use cases.

For example, Mark Text is problematic with existing files that are managed under Git. You can't edit only the parts that need to be be edited. Mark Text Introduces extra unexpected, and unwanted changes.

**Comment by aukeroorda** [comment]
Also modified when toggling source code mode. Exported PDF is also modified, but doesn't change text buffer. Makes it unusable, as it partially removes footnotes (Pandoc-style enabled), and moves the remaining half to a different location, in between list items... Would be nice if we could just disable this completely in the options untill there is a better interface for it.

**Comment by N0rbert** [comment]
https://github.com/marktext/marktext/issues/2035 is still a problem. 

Can't use MarkText with correctly written documents placed in Git repository. 
MarkText still replaces `1.`'s with `1.`,  `2.`, `3.` and so on in numbered lists (which is completely wrong and violates `ordered-list-marker-value` rule from `remark-lint` and `MD029` from `mdl`). 
Also MarkText adds empty lines between numbered list items - it is bug https://github.com/marktext/marktext/issues/2479 .
MarkText adds trailing spaces before the first unnumbered list item - it is bug https://github.com/marktext/marktext/issues/2480 .

So MarkText behavior may break CI/CD workflow involving `remark-lint` and/or `mdl` as syntax checker(s).

**Comment by dave-kennedy** [comment]
@axelsimon that's the "loose" list setting, which you can enable or disable under Preferences > Markdown. Unrelated to this issue, I think, unless Mark Text adds the extra line breaks automatically when opening a document.

**Comment by brainchild0** [comment]
> @axelsimon that's the "loose" list setting, which you can enable or disable under Preferences > Markdown. Unrelated to this issue, I think, unless Mark Text adds the extra line breaks automatically when opening a document.

Perhaps my question is off topic, but should the choice of loose versus tight list be one that may be selected for the particular list, rather than determined by a configuration option?

**Comment by N0rbert** [comment]
Still not fixed in 0.16.3.

**Comment by ghostbody** [comment]
I make a workaround by deleting these lines and then build the app again, and I fix it.

https://github.com/marktext/marktext/blob/develop/src/main/filesystem/markdown.js#L113

@jgato may this help you.

**Comment by N0rbert** [comment]
Still not fixed in v0.17.0-rc.1.

**Comment by mustafacanp** [comment]
After the `Typora` switched to the premium version I tried first `marktext` as an alternative. But this issue made me give up.

**Comment by jgato** [comment]
This issue is causing me many troubles, because of working on MD on GIT repos :( I tried to build the repo by myself with some of the workaround, but i failed. Maybe I will try again later..

**Comment by ghostbody** [comment]
I take a glance at the code.

The lexer paser implementation does not remain the source.

The code is here: https://github.com/marktext/marktext/blob/develop/src/muya/lib/parser/marked/lexer.js#L117


It seems like a big work to fix this issue...

**Comment by N0rbert** [comment]
@ghostbody  Then this editor is just another hipster's toy, not a real-life editor. 
Possible alternatives are [ReText](https://github.com/retext-project/retext) and [VNote](https://github.com/vnotex/vnote). The last free version of [Typora - 0.11.18](https://typora.io/linux/linux/typora_0.11.18_amd64.deb) may be an alternative too.
Table editing with column moving may be done in any plain text editor with block selection - for example in [Kate](https://kate-editor.org/).

**Comment by ghostbody** [comment]
@N0rbert Typora took the first place 😃

**Comment by brainchild0** [comment]
> Then this editor is just another hipster's toy, not a real-life editor.

I think it is not productive to make general denouncements against the quality of the application. The difficulties with usability have been acknowledged by the project maintainers. 


No one is required to use the software in this project.  Currently, the choices are to use MarkText, to use another editor instead, or to use none. 

If the choices are   not suitable for your purposes, if you wish  to see improvements in the project, then the most ethical and practical approach is to support the efforts of those contributing to it, if not to make a contribution yourself.

Comments toward other objectives should probably be given in other venues.

**Comment by yh-Sun** [comment]
当我满怀期待使用marktext时，纯英文的配置信息让我很艰难，现在又出现一个无法解决且核心的用户问题，心里有些很失落。

**Comment by yh-Sun** [comment]
When I was looking forward to using marktext, the configuration information in pure English made me very difficult, and now there is an unsolvable and core user problem, and I feel a little lost.

**Comment by yanzhuo0323** [comment]
Still not fixed v0.17.1. 
:fire::fire::fire:

**Comment by ivenhov** [comment]
At the moment this is the only thing that prevents me from using MarkText.
Opening a document to edit small part (spelling mistake) causes many changes.
Particularly bad for tables, where last column of every row is bloated with whitespaces to match widest of the columns.
Widespread changes makes awkward to commit the document back to git.
Sharing markdown documents with other people, potentially using different applications is also problematic due to conflicting changes.

**Comment by yunnysunny** [comment]
I have to revert the changes cased by view manual before commit to git.

**Comment by liqiwenx** [comment]
One year passed,  may any update about this issue? This problem makes it difficult for users to use. I like this project & hope it to greater.

**Comment by About7Deaths** [comment]
I use Obsidian as my primary markdown editor, and MarkText as secondary. MarkText keeps trying to change the format of my Obsidian markdown files, when I only want to use the application for quickly viewing markdown files within my file system explorer in Windows. Would it be possible to enable some kind of always-view-only mode to bypass this? I don't even need to edit any of the files within MarkText...

**Comment by AaronKnowls** [comment]
Are there any updates on this?
Also, has this software been discontinued?

**Comment by HEI-cloud** [comment]
难以想象这个问题，从21年讨论到了23年也依旧还在，好久没有发布新版本了，不知道活跃度到底如何

**Comment by N0rbert** [comment]
Probably we have to switch to [VNote](https://github.com/vnotex/vnote) or [ReText](https://github.com/retext-project/retext). They lack only one feature - WYSIWYG table editing.

**Comment by palto42** [comment]
> Probably we have to switch to [VNote](https://github.com/vnotex/vnote) or [ReText](https://github.com/retext-project/retext). They lack only one feature - WYSIWYG table editing.

Looks interesting, but does Vnote have a WYSIWYG edit mode at all? Just tried latest release (not nightly) and seems to have one text edit mode with side by side preview.

**Comment by N0rbert** [comment]
Still happens with 0.17.1. 
Project seems to be abandoned. Developers, please give some comments on this.

**Comment by yunnysunny** [comment]
I have switched to [obsidian](https://obsidian.md/).

**Comment by Dane411** [comment]
@yunnysunny the same issue appears in Obsidian
https://forum.obsidian.md/t/last-modified-time-updating-misbehavior/38976

**Comment by yunnysunny** [comment]
> @yunnysunny the same issue appears in Obsidian https://forum.obsidian.md/t/last-modified-time-updating-misbehavior/38976

I have read the issue on obsidian, it's not the same problem.

**Comment by gatspy** [comment]
every time open a file, it prompts me to save it when I close it, which is very annoying.

**Comment by elzik** [comment]
I use Markdown files created by Azure Devops, GitHub, Obsidian and others.

This automated formatting makes MarkText overly opinionated and means I cannot use it. It's a shame because otherwise, it seems like a great tool.

**Comment by awxiaoxian2020** [comment]
Do we have some workaround for this? Maybe we can get help from LLM?

**Comment by N0rbert** [comment]
I'm editing this comment again to say that mdSilo from https://github.com/mdSilo/mdSilo-app is not an option. 
It has WYSIWYG table editing, but also it made my 45 Kb real world document bad formatted and both remark and mdl linters are not happy with it. Reported [an issue](https://github.com/mdSilo/mdSilo-app/issues/781) to their github.

I'll continue to use ReText and Kate.

**Comment by stulluk** [comment]
My build has caused random segfaults, therefore I ended up using: https://github.com/Tkaixiang/marktext

**Comment by BlohoJo** [comment]
I work with a lot of markdown files. This is a great viewer. But, I can't have it prompt me to save changes on every single file when I only view it and don't touch it. That's a deal breaker. I'll have to look for another viewer that doesn't do this.

I switched to [Markpad](https://github.com/alecdotdev/Markpad). 😕

**Comment by zac15987** [comment]
> every time open a file, it prompts me to save it when I close it, which is very annoying.

> I work with a lot of markdown files. This is a great viewer. But, I can't have it prompt me to save changes on every single file when I only view it and don't touch it. That's a deal breaker. I'll have to look for another viewer that doesn't do this.

I've fixed the "Save?" dialog issue in my fork. Files opened for viewing will no longer be falsely marked as modified, so you won't see the prompt when closing without making any edits.

The root cause was that Muya's markdown round-trip (parse → export) produced output differing from the original file, triggering a false "modified" state. The fix adds an `isJustLoaded` flag that suppresses this first false-positive detection after loading a file from disk.

Release: [v0.17.2](https://github.com/zac15987/marktext/releases/tag/v0.17.2)

**Comment by chaosink** [comment]
> > every time open a file, it prompts me to save it when I close it, which is very annoying.
> 
> > I work with a lot of markdown files. This is a great viewer. But, I can't have it prompt me to save changes on every single file when I only view it and don't touch it. That's a deal breaker. I'll have to look for another viewer that doesn't do this.
> 
> I've fixed the "Save?" dialog issue in my fork. Files opened for viewing will no longer be falsely marked as modified, so you won't see the prompt when closing without making any edits.
> 
> The root cause was that Muya's markdown round-trip (parse → export) produced output differing from the original file, triggering a false "modified" state. The fix adds an `isJustLoaded` flag that suppresses this first false-positive detection after loading a file from disk.
> 
> Release: [v0.17.2](https://github.com/zac15987/marktext/releases/tag/v0.17.2)

@zac15987 Thanks for the fix! Why not submit a pull request?

**Comment by zac15987** [comment]
> @zac15987 Thanks for the fix! Why not submit a pull request?

Thanks. I'll submit a PR soon!

**Comment by N0rbert** [comment]
With the 0.20.0~beta.4 the saved real-world document gets many warnings from the linters:

* 71 `ordered-list-marker-value remark-lint` (remark: 15.0.1, remark-cli: 12.0.1) aka `MD029 Ordered list item prefix` (mdl 0.12.0) - see https://github.com/marktext/marktext/issues/4772 ;

Also  code listing loses attributes - see https://github.com/marktext/marktext/issues/4770 .

**Comment by awebeer256** [comment]
I've got two specific pet peeves that fall under this discussion.

1. MarkText inserts blank lines between HTML-style comments on consecutive lines. In other words, if I want the raw text to look like this:

```
<!-- foo -->
<!-- bar -->
```
Then MarkText changes it to this:

```
<!-- foo -->

<!-- bar -->
```
2. MarkText adds four leading spaces for each level of nested list, when I would prefer two. If I want this:

```
- foo
  - bar
- baz
```
Then MarkText changes it to this:

```
- foo
    - bar
- baz
```

*Ninja edit: this is not with the new beta.*
