### ISSUE TITLE
RFC and development plan for sessions

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#988]
Development plan for sessions:

- [ ] Refactor main source code
  - [ ] Refactor file structure
  - [ ] Replace `log`
  - [ ] Refactor `globalSetting` into `appPath` and `appEnv`
  - [ ] Remove `textDirection`/`getDefaultTextDirection()` from `filesystem.js` and tab state (renderer)
- [ ] Use a lightweight argument parser like `arg` or `minimist`
- [ ] Allow to change the application data directory
  - [ ] with support for portable mode

Branch `sessions`:

- [ ] Change application data directory structure (see below)
- [ ] Implement sessions (see below)
- [ ] File backup and recovery (#732)
  - [ ] Automatically backups (see below)
  - [ ] `safeSaveDocuments` setting to atomic save files using a temporary file and `rename` syscall that atomic move the file on the *same* filesytem (either the old file or new file exist if the application/OS crashes)
- [ ] Add unit tests
- [ ] Testing

The following two comments contain the session RFC and high-level technical design (inspired by vscode workspaces).

**Comment by fxha** [comment]
# Session

## Overview

A session contains a persistent state of the window layout, editor configuration and file information:

- window state like position
- layout configuration
- root folder
- opened tabs
  - unsaved changes
  - tab/file configuration like encoding and line ending

At a later stage we can also save the cursor position, file history and side bar states like opened folders in tree view etc.

Mark Text runs as a single-instance and each window is associated with one unique session. Extensions and Mark Text can save further files in the session or global, accessible for all sessions. Mark Text allows to spawn multiple instances if the instance has a different application data directory than all started instances.

All active sessions are restored after a forced restart, forced shutdown, crash or similar (hereinafter as "forced restart") but configuration/file changes may be lost up to a certain point. Starting Mark Text after closing gracefully load the last active session (= last active window with associated session). Sessions are saved in the application data directory that can be changed with `--user-data-dir <dir>` - the path must be writeable.

### Unsaved changes

Unsaved file/tab changes are automatically saved after some time/when closing the window and restored during application start when using a persistent session or workspace. If a file has been changed externally after saving unsaved changes an notification is display but the file is restored as usual.

### Automatically restore

Sessions are loaded/restored during application start. Restore of unsaved changes or sessions can be disabled by setting `restoreChangesOnStart` and/or `restoreSessionOnStart` (= command-line flag `--nosession`) to `false`. If `restoreChangesOnStart` is set to `true` but not `restoreSessionOnStart` a temporary session is used for each window until application shutdown. If both are set to `false` neither sessions nor backups are created (but may a in-memory session is used?).

### Persistent session

Persistent sessions are used by Mark Text and are identified by a hashed normalized directory path using SHA1-Hex. A lower-case directory path is used on macOS and Windows because the filesystem API is case-insensitive by default (normally we need to check for the filesystem type and OS configuration). E.g. if the same directory is opened later on the last state is restored without loading a particular session. A persistent session may be delete if it was not use for a long time and is not an active session or can be explicitly deleted by the user.

### Temporary session

A temporary session can be created via `-n` or `--new-window` flag or via menu `File -> New Window`. Temporary sessions are persistent as long as Mark Text is not closed and deleted on application start if it's not an active session. Temporary sessions use random IDs with a different length than persistent sessions. Selecting a (new) directory in a window load or create a persistent session - the old session is closed/temporary session is discarded.

### Workspace

A workspace is a user-defined persistent session that is created by the user with a user-defined name and never deleted by Mark Text. There is no technical difference between persistent sessions and workspaces. Workspaces can be used to save various directories and easy switch between these.

**TODO:** Should we add a `group` entry for workspaces to allow (sub)categories?

### Active session

An active session is not another session type but rather a session that is currently opened and may be multiple sessions if multiple windows are opened. Meaning even a temporary session that was opened in a window is restored if Mark Text is forced to restart.

## Session Management

A session (not workspace) is created only by Mark Text and may be deleted and loaded via command-line.

`-s` or `--session`:

- Load a session by ID: `marktext --session <id>`
- Load multiple sessions or workspaces by ID and create a window per session: `marktext --session load <IDs>`
- Delete a given session by ID: `marktext --session delete <id>`
- List all sessions: `marktext --session list`

## Workspace Management

A workspace can be created, deleted and loaded via command-line (`-w` or `--workspace`) or GUI.

### Command-line

`marktext -w <option> <name>`

**Option:**

- `create`: Create a workspace. `<name>` is used as session label and the MD5 hashed workspace name as session id.
- `rename`: Rename the given workspace; e.g: `marktext -w rename <old-workspace-name> <new-workspace-name>`.
- `delete`: Delete the given workspace.
- `list`: List all workspaces but not sessions.
- `add`: Add the file(s) to the given workspace, e.g: `marktext -w add <workspace-name> <files>`.
- No *option* parameter: Open the given workspace in a new window.

**Workspace name:**

The workspace name is used to identify the workspace and can only be used once. `load` and all option parameters are reserved names and cannot be used.

### GUI

No GUI interface is planned yet but we should add a "Project Management" panel to the side bar or via quick open or dialog later.

## Command-line

When opening a file via command-line...

- the associated tab is selected and the window is focused. If the file is opened in multiple windows the last active window is focused and the associated tab is selected. *NOTE:* Opening the same file in multiple sessions may lead to inconsistencies! 
- the file is added to the session of the last active/focused window.
- and `--session <id>` or `--workspace <name>` is also passed, the file is added to the specified session or workspace and opened in a new window.

Opening a directory via command-line or GUI load or create the associated session.

```
# The last active session is restored if Mark Text is not started or the last active window is focused.
marktext

# Create a new temporary session and open a new window.
marktext --new-window <dir|file(s)>

# See above paragraph.
marktext <file(s)>

# Create or load the associated session and open a new window.
marktext <dir>

# Open or focus the given session in a new window.
marktext --session <id> <files>

# Open or focus the given workspace in a new window.
marktext --workspace <name> <files>
```

## IPC

We using Electrons `app.requestSingleInstanceLock()` method to spawn a single-instance because currently no additional inter-process communication is needed.

**Comment by fxha** [comment]
# Session (Technical Design)

## Overview (application data directory)

```
marktext/
├── electronUserData/ ("app.getPath('userData')")
├── globalStorage/ (global storage for all sessions)
├── logs/
│   ├── <year><month>/
│       └── log files, e.g. for main, (each?) renderer, perf and debuf stuff
│   └── ...
├── preferences/ (planned for v0.16.0)
│   ├── keybindings.json
│   └── settings.json
├── themes/ (planned for v0.16.0)
├── extensions/ (planned for v?)
├── sessions/
│   ├── sessions.json
│   ├── <id>/ (see below)
│   └── ...
└── tmp/ (optional - default tmp directory is the OS one)
```

**sessions.json:**

When Mark Text is closed gracefully only one session (the last window) is saved but while Mark Text is running all active session IDs are saved.

```json
[
  "<session-id>",
  // ...
]
```

## Session structure

```
<session>/
├── recovery/
│   ├── <file-id> (backup of <file-id>)
│   └── ...
├── storage/ (storage for current session)
├── session.json
├── settings.json (reserved for upcomming settings to override global settings)
├── tabs.json
├── recently-used-documents.json (Linux and Windows only)
└── window-state.json
```

**Session ID:**

- *Temporary session:* `uuidv4()` (36 characters)
- *Persistent session:* `sha1hex(path.normalize(isLinux ? (absolute)rootFolder : (absolute)rootFolder.toLowerCase()))` (40 characters)
- *Workspace session:* `md5hex(<workspace name>)` (32 characters)

**session.json:**

```json
{
  "version": number,
  "id": string,
  // type --> check id length
  "label": string|null,
  "rootFolder": string|null,
  // Optional
  "views": {
    "sideBar": {
      "visible": boolean,
      "width": number,
      "activeViewId": string (???)
    },
    "tabBar": {
      "visible": boolean
    }
  }
}
```

**tabs.json:**

```json
{
  "selectedIndex": number,
  "tabs": [
    {
      "type": enum<0: untitled, 1: file>,
      // The file path or untitled tab label (untitled-<number> in lower-case).
      "path": string,
      "lf": string
      // Add more information at a later state.
    },
    // ...
  ]
}
```

**TODO:** Should we include *tabs* in `session.json`?

### File Recovery

The `recovery` directory contains a full file backup of unsaved file/tab changes identified by `sha1hex(path.normalize(isLinux ? (absolute)filePath : (absolute)filePath.toLowerCase()))` or `untitled-<number>` for untitled tabs.

**Comment by Jocs** [comment]
> Unsaved file/tab changes are automatically saved after some time/when closing the window and restored during application start when using a persistent session or workspace.

Do you mean that if I didn't save the tab/file, I can still close window. the file content saved to session?

>If a file has been changed externally after saving unsaved changes an notification

How do you know that the file has been changed by other editor ?

**Comment by Jocs** [comment]
>Should we include tabs in session.json?

I agree to include tabs.json into session.json.

@fxha Can we save all `setting`, `keybinding` and `session` in [electron-store](https://github.com/sindresorhus/electron-store)? So we do not need the `json` files?

**Comment by fxha** [comment]
> Do you mean that if I didn't save the tab/file, I can still close window. the file content saved to session?

Yes, as long as it's not a temporary session but unsaved changes are bound to the session. If you `File -> Open Folder` the same folder the same persistent sessions is loaded because a persistent session represent a directory on disk.

E.g. you are using session `A` and `file-1` has unsaved changes, then you open another session and open `file-1` too. The changes from session `A` are not restored but if you open session `A` again they are restored.

> How do you know that the file has been changed by other editor ?

This only applies when Mark Text is closed. We can compare the last modification time from both files (`fs.stat`).

> Can we save all setting, keybinding and session in electron-store? So we do not need the json files?

I think we should still separate settings and key bindings. `electron-store` save the data as JSON file, so we can create multiple stores but after reviewing the code we might have another problem. The library reads after each `get` and not just after the file has changed externally. I think we can start using `electron-store` for settings and pass changed to renderer (as currently) and later replace `electron-store` with an optimized fork that only reads the file after a change occurred.

For session I'll create a custom `SessionStorage` class or so that is especially for sessions. I have a rough idea how I'll implement that.

**Comment by Jocs** [comment]
>The library reads after each get and not just after the file has changed externally. 

Do you mean this maybe cause performance issue?

**Comment by fxha** [comment]
Yes, I think so.

**Comment by Jocs** [comment]
I think you can adjust the main folder structure first, then submit a PR, I can also take a look, then add some code of Mark Text Preference.

**Comment by Jocs** [comment]
@fxha Do you have plan to do this in version 0.16.0?

**Comment by fxha** [comment]
Currently not planned.

**Comment by Jocs** [comment]
Thank you for this detailed RFC. This issue has been open since 2019 with no active implementation, and the core team indicated in September 2019 that it was not planned for the near term. The most critical user need from this RFC — recovering unsaved changes after a crash — is now partially addressed by the `editorBufferStore` mechanism introduced during the engine rewrite (per-window tab state is saved atomically to disk and restored on next launch). The full session system as designed here (persistent sessions tied to directory paths, temporary/workspace sessions, background I/O process, `--session` CLI management) has not been built and there is no current plan to do so. Given the age of this RFC and the significant engineering investment it would require, we are closing this issue as stale. If there is community interest in revisiting specific pieces (e.g. workspace support or crash recovery improvements), please open a focused new issue with a concrete scope.
